import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useEffect, useState } from "react";
const link =
  "https://api.x.immutable.com/v1/assets?page_size=10&collection=0xacb3c6a43d15b907e8433077b6d38ae40936fe2c";
export default function Home({ data }) {
  const [nextCursor, setNextCursor] = useState(data.cursor);
  const [newData, setNewData] = useState(data);
  const nextPageHandler = async () => {
    const res = await fetch(`${link}&cursor=${nextCursor}`, {
      method: "GET",
      headers: {
        "Content-Type": "application/json",
      },
    })
      .then((r) => r.json())
      .catch((err) => {
        console.error(err);
      });
    setNewData(res);
    setNextCursor(res.cursor);
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <button disabled={nextCursor.remaining === 0} onClick={nextPageHandler}>
        Next page
      </button>
      <div className={styles.grid}>
        {newData.result?.map((d) => {
          return (
            <a href="#" className={styles.card} key={d.id}>
              <Image src={d.image_url} width="300px" height="400px" />
              <h2>{d.name}</h2>
              <p>{d.user}</p>
            </a>
          );
        })}
      </div>
    </div>
  );
}

export async function getStaticProps() {
  const res = await fetch(link, {
    method: "GET",
    headers: {
      "Content-Type": "application/json",
    },
  })
    .then((r) => r.json())
    .catch((err) => {
      console.error(err);
    });
  return {
    props: {
      data: res,
    },
  };
}
